version: '2'

services:
  proxy:
    image: alexanderkrause/rpi-nginx-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    restart: on-failure

  letsencrypt-companion:
    image: alexanderkrause/rpi-letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    depends_on:
      - proxy
    volumes_from:
      - proxy
    environment:
       - NGINX_PROXY_CONTAINER=proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs:rw
    restart: on-failure

  web:
    image: armhfbuild/nginx
    container_name: nextcloud_webserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST=YourDomain
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=SameAsYourDomain
      - LETSENCRYPT_EMAIL=EmailofYourDomain
      - LETSENCRYPT_KEYSIZE=4096 (change as desired)
    networks:
      - proxy-tier
    restart: on-failure

  app:
    image: nextcloud:fpm
    container_name: nextcloud_fpm
    links:
      - db
    volumes:
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
    environment:
      - NEXTCLOUD_UPDATE=1
    networks:
      - proxy-tier
    restart: on-failure

  db:
    image: jsurf/rpi-mariadb
    container_name: db
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    
    environment:
      - MYSQL_ROOT_PASSWORD=YourSuperSecretPassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=YourSecondSecretPassword
    networks:
      - proxy-tier
    restart: on-failure

networks:
  proxy-tier:
    external:
      name: nginx-proxy
